# Generated by Django 6.0.5 on 2026-05-10 17:56

from decimal import Decimal

import django.core.validators
from django.db import migrations, models

import orm.pk


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=orm.pk.uuid7, editable=False, primary_key=True, serialize=False)),
                ("restaurant_id", models.UUIDField(db_index=True, verbose_name="restaurant id")),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("description", models.TextField(blank=True, default="", verbose_name="description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="price",
                    ),
                ),
                ("category", models.CharField(max_length=64, verbose_name="category")),
                ("image_url", models.URLField(blank=True, default="", max_length=500, verbose_name="image url")),
                ("is_available", models.BooleanField(default=True, verbose_name="is available")),
            ],
            options={
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
                "indexes": [
                    models.Index(fields=["restaurant_id", "is_available"], name="catalog_dis_restaur_d910d3_idx")
                ],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("price__gte", 0)), name="dish_price_non_negative")
                ],
            },
        ),
    ]
