# Generated by Django 6.0.3 on 2026-03-18 22:13

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True, verbose_name="email address"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name="phone number"
                    ),
                ),
                ("verification_code", models.CharField(db_index=True, max_length=6, verbose_name="verification code")),
                ("secret_code_hash", models.CharField(max_length=64, verbose_name="secret code hash")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="expires at")),
                ("is_used", models.BooleanField(default=False, verbose_name="is used")),
            ],
            options={
                "verbose_name": "OTP code",
                "verbose_name_plural": "OTP codes",
                "indexes": [
                    models.Index(fields=["email", "verification_code", "is_used"], name="users_otpco_email_02621a_idx"),
                    models.Index(fields=["phone", "verification_code", "is_used"], name="users_otpco_phone_23b0d7_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("email__isnull", False), ("phone__isnull", False), _connector="OR"),
                        name="otp_has_email_or_phone",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("email__isnull", False), ("phone__isnull", True)),
                            models.Q(("email__isnull", True), ("phone__isnull", False)),
                            _connector="OR",
                        ),
                        name="otp_has_email_xor_phone",
                    ),
                ],
            },
        ),
    ]
